/*
Resources file that maps names to each file in the resources file.
Sprites are mapped to consts based on their path in the resource file. i.e.
images/path/to/file.jpg -> IMG_PATH_TO_FILE
*/


/************
Resource IDs header. This was generated by update.py and contains information
on the locations of resources for loading, generated resource enum names, and
animation info. Later, I plan on making the storage for all this stuff more
efficient (especially animations), but for now I just want it to work.

DON'T MANUALLY CHANGE THE FILE! This file will be overwritten every build
************/

#ifndef __RESOURCE_IDS__


#include <string>
#include <engine.h>

#define __RESOURCE_IDS__

#ifndef __COLL_ENUM__
#define __COLL_ENUM__
// This is an int to allow us to store it in the collision data array
enum CollisionType : int
{
  COLLISION_NONE,
  COLLISION_BOUNDING_BOX,

  COLLISION_COUNT
};
#endif


