/*
Resources file that maps names to each file in the resources file.
Sprites are mapped to consts based on their path in the resource file. i.e.
images/path/to/file.jpg -> IMG_PATH_TO_FILE
*/


/************
Resource IDs header. This was generated by update.py and contains information
on the locations of resources for loading, generated resource enum names, and
animation info. Later, I plan on making the storage for all this stuff more
efficient (especially animations), but for now I just want it to work.

DON'T MANUALLY CHANGE THE FILE! This file will be overwritten every build
************/

#ifndef __RESOURCE_IDS__


#include <string>
#include <engine.h>

#define __RESOURCE_IDS__

#ifndef __COLL_ENUM__
#define __COLL_ENUM__
// This is an int to allow us to store it in the collision data array
enum CollisionType : int
{
  COLLISION_NONE,
  COLLISION_BOUNDING_BOX,

  COLLISION_COUNT
};
#endif


////////// Images //////////
enum ResourceImage: unsigned int
{
 IMG_CROSS,
 IMG_SUBDIR1_SUBDIR2_SUBDIRIMAGE,
 IMG_TESTIMAGE,
 IMG_COOKIEMONSTER,

 IMG_COUNT
};

std::string IMAGE_PATHS[] = { 
  "resources/images/cross.png",
  "resources/images/subdir1/subdir2/subdirimage.png",
  "resources/images/testimage.png",
  "resources/images/cookiemonster.png"
};

////////// ANIMATIONS //////////
enum ResourceAnimation: unsigned int
{
 ANIM_CROSS_SPIN,
 ANIM_CROSS_TATER,
 ANIM_COOKIEMONSTER_STILL,

 ANIM_COUNT
};

AnimationStripConfig PREDEFINED_ANIMATIONS[] = {
  {IMG_CROSS, 0, 0, 32, 32, 0, 0, 4, 4},
  {IMG_CROSS, 0, 0, 32, 32, 0, 0, 2, 2},
  {IMG_COOKIEMONSTER, 0, 0, 250, 224, 0, 0, 1, 1}
};

const unsigned int PREDEFINED_COLLISION_DATA[] = {
  // ANIM_CROSS_SPIN
  COLLISION_BOUNDING_BOX, 0, 0, 1, 1,
  COLLISION_BOUNDING_BOX, 31, 31, 1, 1,
  // ANIM_CROSS_TATER
  COLLISION_BOUNDING_BOX, 0, 0, 14, 12
};

const int PREDEFINED_COLLISION_DATA_LOC[][2] = {
  // ANIM_CROSS_SPIN
  {0, 5},
  {0, 5},
  {5, 5},
  {5, 5},
  // ANIM_CROSS_TATER
  {0, 0},
  {10, 5}
};

// Stores the index+1 of where in the data_loc array each frame is. It
// stores index+1 of the array so that we can use 0 to tell the program to create
// its own bounding box
const unsigned int PREDEFINED_COLLISION_DATA_FRAME[] = {
  // ANIM_CROSS_SPIN
  1,

  // ANIM_CROSS_TATER
  5,

  // ANIM_COOKIEMONSTER_STILL
  0
};

const char ANIMATION_HAS_COLLISION[] = {
  // ANIM_CROSS_SPIN
  true,

  // ANIM_CROSS_TATER
  true,

  // ANIM_COOKIEMONSTER_STILL
  true
};

////////// Sounds //////////
enum ResourceSound: unsigned int
{

 SND_COUNT
};

std::string SOUND_PATHS[] = {
};


#endif
